# Generated by Django 5.1.1 on 2024-09-21 15:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(db_collation='case_insensitive', max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('social', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, null=True, size=None)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='Common.image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.image')),
            ],
            options={
                'verbose_name': 'creator',
                'verbose_name_plural': 'creators',
                'db_table': 'creators',
            },
        ),
        migrations.CreateModel(
            name='CreatorFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='Creator.creator')),
            ],
            options={
                'verbose_name': 'creator follower',
                'verbose_name_plural': 'creator followers',
                'db_table': 'creator_followers',
            },
        ),
    ]
