# Generated by Django 5.1.1 on 2024-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creator', '0002_creator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorfollower',
            name='notifications',
            field=models.CharField(choices=[('all', 'All'), ('none', 'None'), ('personalized', 'Personalized')], default='personalized', max_length=255),
        ),
    ]
