# Generated by Django 5.1.1 on 2024-09-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE COLLATION IF NOT EXISTS public.case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false);")
    ]
