# Generated by Django 5.1.1 on 2024-09-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('type_of', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('link', 'Link'), ('poll', 'Poll'), ('event', 'Event')], default='text', max_length=20)),
                ('type_of_id', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('scheduled', 'Scheduled')], default='published', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostClap',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post clap',
                'verbose_name_plural': 'post claps',
                'db_table': 'post_claps',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'post comment',
                'verbose_name_plural': 'post comments',
                'db_table': 'post_comments',
            },
        ),
        migrations.CreateModel(
            name='PostCommentVote',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('vote', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post comment vote',
                'verbose_name_plural': 'post comment votes',
                'db_table': 'post_comment_votes',
            },
        ),
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post event',
                'verbose_name_plural': 'post events',
                'db_table': 'post_events',
            },
        ),
        migrations.CreateModel(
            name='PostEventAttendee',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post event attendee',
                'verbose_name_plural': 'post event attendees',
                'db_table': 'post_event_attendees',
            },
        ),
        migrations.CreateModel(
            name='PostEventSpeaker',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post event speaker',
                'verbose_name_plural': 'post event speakers',
                'db_table': 'post_event_speakers',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post image',
                'verbose_name_plural': 'post images',
                'db_table': 'post_images',
            },
        ),
        migrations.CreateModel(
            name='PostImageObj',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'post image obj',
                'verbose_name_plural': 'post image objs',
                'db_table': 'post_image_objs',
            },
        ),
        migrations.CreateModel(
            name='PostPoll',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post poll',
                'verbose_name_plural': 'post polls',
                'db_table': 'post_polls',
            },
        ),
        migrations.CreateModel(
            name='PostPollVote',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('option', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post poll vote',
                'verbose_name_plural': 'post poll votes',
                'db_table': 'post_poll_votes',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('key', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryClap',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'story clap',
                'verbose_name_plural': 'story claps',
                'db_table': 'story_claps',
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'story comment',
                'verbose_name_plural': 'story comments',
                'db_table': 'story_comments',
            },
        ),
        migrations.CreateModel(
            name='StoryCommentVote',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('vote', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'story comment vote',
                'verbose_name_plural': 'story comment votes',
                'db_table': 'story_comment_votes',
            },
        ),
    ]
