# Generated by Django 5.1.1 on 2024-09-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Common', '0001_initial'),
        ('Content', '0001_initial'),
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creator'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Common.tag'),
        ),
        migrations.AddField(
            model_name='postclap',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.post'),
        ),
    ]
