# Generated by Django 5.1.1 on 2024-09-21 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Common', '0001_initial'),
        ('Content', '0002_initial'),
        ('Creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postclap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.creator'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.postcomment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.postcomment'),
        ),
        migrations.AddField(
            model_name='postcommentvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postevent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.post'),
        ),
        migrations.AddField(
            model_name='posteventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.postevent'),
        ),
        migrations.AddField(
            model_name='posteventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posteventspeaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.postevent'),
        ),
        migrations.AddField(
            model_name='posteventspeaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.post'),
        ),
        migrations.AddField(
            model_name='postimageobj',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.image'),
        ),
        migrations.AddField(
            model_name='postimageobj',
            name='to_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.postimage'),
        ),
        migrations.AddField(
            model_name='postpoll',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.post'),
        ),
        migrations.AddField(
            model_name='postpollvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.postpoll'),
        ),
        migrations.AddField(
            model_name='postpollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.creator'),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.category'),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.image'),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Common.tag'),
        ),
        migrations.AddField(
            model_name='storyclap',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.story'),
        ),
        migrations.AddField(
            model_name='storyclap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Creator.creator'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.storycomment'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.story'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycommentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.storycomment'),
        ),
        migrations.AddField(
            model_name='storycommentvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
