# Generated by Django 5.1.1 on 2024-09-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '__first__'),
        ('Content', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimageobj',
            options={'verbose_name': 'post image object', 'verbose_name_plural': 'post image objects'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_of_id',
        ),
        migrations.RemoveField(
            model_name='postevent',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimageobj',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='postimageobj',
            name='to_image',
        ),
        migrations.RemoveField(
            model_name='postpoll',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='type_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.postimage'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Content.postpoll'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='images',
            field=models.ManyToManyField(through='Content.PostImageObj', to='Common.image'),
        ),
        migrations.AddField(
            model_name='postimageobj',
            name='post_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Content.postimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
