# Generated by Django 5.1.1 on 2024-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_alter_postpollvote_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storycomment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
