# Generated by Django 5.1.1 on 2024-09-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_alter_postcomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Content.story'),
        ),
    ]
