# Generated by Django 5.1.1 on 2024-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Content', '0007_alter_post_author_alter_postclap_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='new_images',
            field=models.ManyToManyField(related_name='new_images', to='Common.image'),
        ),
    ]
