# Generated by Django 5.1.1 on 2024-10-04 15:46

from django.db import migrations

def copy_images(apps, schema_editor):
    PostImage = apps.get_model('Content', 'PostImage')
    for post_image in PostImage.objects.all():
        post_image.new_images.set(post_image.images.all())
        post_image.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_postimage_new_images'),
    ]

    operations = [
        migrations.RunPython(copy_images),
    ]

    
       