# Generated by Django 5.1.1 on 2024-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Content', '0009_auto_20241004_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='images',
            field=models.ManyToManyField(related_name='images', to='Common.Image'),
        ),
        migrations.DeleteModel(
            name='PostImageObj',
        ),
    ]